# This is a basic workflow to help you get started with Actions

name: 部署到阿里云服务器

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: 迁出代码
        uses: actions/checkout@v3
      
      # 安装nodejs
      - name: 安装nodejs
        uses: actions/setup-node@v1
        with: 
          node-version: 14.0.0
      
      # 安装依赖
      - name: 安装依赖
        run: npm install
        
      # 打包
      - name: 打包
        run: npm run build

      # 开始发布
      - name: 发布阿里云
        uses: easingthemes/ssh-deploy@v2.1.1
        env: 
          # 私钥
          SSH-PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          # scp参数
          ARGS: '-avzr --delete'
          #源目录
          SOURCE: 'dist'
          # 服务器ip
          REMOTE_HOST: ${{ secrets.HZZY_BLOG }}
          # 用户
          REMOTW_USER: 'root'
          TARGET: '/www/wwwroot/blog.hzzy.xyz'
